pipeline {
    agent any

    environment {
        IMAGE_NAME = "ritheesh007/billing-app"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Ritheeshselva/Consultancy.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('bill-ui') {
                    bat 'docker build -t %IMAGE_NAME% .'
                }
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                bat 'docker push %IMAGE_NAME%'
            }
        }
    }
}